# Activation

激活层的作用是增加神经网络中的非线性。如果去掉激活层，神经网络中大部分运算就只是线性的，层数再深，效果也等同于单层线性模型。实际上，一个简单的线性层加上一个激活函数，与生物学中的一个神经元非常类似。

![Activation](../figs/activation/activation.png)

激活层的作用是引入非线性，因此理论上只要是非线性函数，都有做激活层的潜力。但是，不同的激活函数训练成本是不同的。如我们通常希望激活函数可微以方便进行反向传播更新参数。

常见的一些激活函数及其特点如下：

## Sigmoid

Sigmoid 的表达式如下：

$$
\operatorname{sigmoid}(x)=\frac{1}{1+e^{-x}}
$$

该函数的特点是值在 $(0,1)$ 之间，并且两端趋于饱和，如下图：

![Sigmoid](../figs/activation/sigmoid.png)

当神经网络的值较大或较小时，其激活后的结果会被映射到函数两端。此时求导后值非常小，因为函数趋于饱和，此时参数更新可能会比较困难。

In [10]:
# sigmoid implementation
import numpy as np

def sigmoid(x):
    """Compute the sigmoid of x.

    Args:
        x: A scalar or numpy array of any size.

    Returns:
        s: sigmoid(x)
    """
    s = 1 / (1 + np.exp(-x))
    return s

x = np.array([-1, 0, 1])
s = sigmoid(x)
print(s)  # Output: [0.26894142 0.5        0.73105858]

[0.26894142 0.5        0.73105858]


## ReLU

ReLU 是一个分段函数，表达式为：

$$
\operatorname{ReLU}(x)=\max(x,0)
$$

其函数图像如下：

![ReLU](../figs/activation/relu.png)

ReLU 的好处是当 $x>0$ 时，函数一直是非饱和的，并且 Sigmoid 的导数值值域为 $[0,0.25]$，而 ReLU 被激活时导数值始终为 1。当网络深度很大，由于导数值最大为 0.25，多层 Sigmoid 容易出现梯度消失的问题；而 ReLU 激活后导数值始终为 1，网络可以做得很深。

ReLU 的缺点在于其非线性很弱，因为它本身是一个分段线性函数。因此如果要效果好，网络需要做得很深。

In [11]:
# relu implementation
def relu(x):
    """Compute the ReLU of x.

    Args:
        x: A scalar or numpy array of any size.

    Returns:
        r: relu(x)
    """
    r = np.maximum(0, x)
    return r
x = np.array([-1, 0, 1])
r = relu(x)
print(r)  # Output: [0 0 1]

[0 0 1]


## Tanh

Tanh（Hyperbolic Tangent，双曲正切）是一种常见的非线性激活函数，可以将任意实数输入映射到 $(-1,1)$ 区间，常用于神经网络的隐藏层。

它的表达式为：

$$
\tanh(x)=\frac{e^x-e^{-x}}{e^x+e^{-x}}
$$

Tanh 函数的图像如下：

![Tanh](../figs/activation/tanh.png)

### Tanh 的特点

Tanh 的输出以 0 为中心：当 $x>0$ 时输出为正，当 $x<0$ 时输出为负，当 $x=0$ 时输出为 0。相比 Sigmoid 的输出范围 $(0,1)$，Tanh 的零中心特性通常更有利于后续神经网络层进行优化。

Tanh 的导数为：

$$
\tanh^{\prime}(x)=1-\tanh^2(x)
$$

其导数范围为：

$$
0<\tanh^{\prime}(x)\leq 1
$$

当 $x=0$ 时，导数取得最大值 1；当 $x\to +\infty$ 或 $x\to -\infty$ 时，Tanh 的输出分别趋近于 1 和 -1，同时导数趋近于 0。

因此，当输入的绝对值较大时，Tanh 会进入饱和区域，梯度变得很小，在深层神经网络中可能产生梯度消失问题。

### Tanh 的优缺点

Tanh 的优点主要是输出以 0 为中心。与 Sigmoid 相比，它的输出范围更大，并且正负输出能够减少后续层输入整体偏向一侧的问题，这通常有助于训练过程更加稳定。

Tanh 的缺点也比较明显：

1. 梯度消失问题：尽管 Tanh 函数在输入接近 0 时梯度较大，但在输入值非常大或非常小的情况下，Tanh 的导数仍然会接近 0，导致梯度消失问题。
2. 计算资源消耗：Tanh 函数涉及指数运算，这可能比其他一些激活函数（如 ReLU）在计算上更加耗时。
3. 初始化敏感性：Tanh 函数对权重初始化较为敏感，如果权重初始化不当，可能会导致梯度消失或爆炸问题。

与 Sigmoid 相比，Tanh 的输出范围更大且以 0 为中心，但两者都属于饱和型激活函数，都可能在输入绝对值较大时出现梯度消失。

In [12]:
# tanh implementation
def tanh(x):
    """Compute the hyperbolic tangent of x.

    Args:
        x: A scalar or numpy array of any size.

    Returns:
        t: tanh(x)
    """
    t = np.tanh(x)
    return t
x = np.array([-1, 0, 1])
t = tanh(x)
print(t)  # Output: [-0.76159416  0.          0.76159416]


[-0.76159416  0.          0.76159416]


## Softmax

Softmax 可以将一个数值向量归一化为一个概率分布向量，且各个概率之和为 1，往往用在神经网络最后一层，将实数输出映射为在各个类别上的概率得分。

对于向量 $x$ 中的第 $i$ 个元素，Softmax 可以表示为：

$$
\operatorname{softmax}(x)_i=\frac{\exp(x_i)}{\sum_j \exp(x_j)}
$$

很多时候，在实际计算 Softmax 前会除以一个 scale 系数，目标是更改 Softmax 的分布。如 scale > 1，那么 Softmax 分布更平滑，反之则更尖锐，不同类别之间的概率差异更加明显。

另外，实际代码计算 Softmax 时通常还会先减去最大值，防止 $\exp(x_i)$ 过大数值溢出：

$$
\operatorname{softmax}(x)_i=\frac{\exp(x_i-\max(x))}{\sum_j \exp(x_j-\max(x))}
$$

In [13]:
# softmax implementation
def softmax(x):
    """Compute the softmax of x.

    Args:
        x: A numpy array of shape (n,).

    Returns:
        s: softmax(x)
    """
    e_x = np.exp(x - np.max(x))  # Subtract max for numerical stability
    s = e_x / e_x.sum(axis=0)
    return s
x = np.array([1.0, 2.0, 3.0])
s = softmax(x)
print(s)  # Output: [0.09003057 0.24472847 0.66524096]

[0.09003057 0.24472847 0.66524096]
